---
format_version: 10
common:
  deploy-tasks: &deploy-tasks
    - exec: 
        command: bash
        arguments:
          - -c
          - echo "Deploy on ${ENV_NAME} environment"

  test-tasks: &test-tasks
    - exec: 
        command: bash
        arguments:
          - -c
          - echo "Running tests on ${ENV_NAME}"
    - exec: 
        command: bash
        arguments:
          - -c
          - docker run --network=host -d -t --name api_test_executor_${ENV_NAME} api_test_executor:latest
    - exec: 
        command: bash
        arguments:
          - -c
          - docker exec api_test_executor_${ENV_NAME} cucumber --tags=@${ENV_NAME} --format html --out test-output/report.html
    - exec: 
        command: bash
        arguments:
          - -c
          - docker cp api_test_executor_${ENV_NAME}:/usr/src/api-tests/test-output/report.html report_${ENV_NAME}.html
    - exec: 
        command: bash
        arguments:
          - -c
          - docker rm -f api_test_executor_${ENV_NAME}


pipelines:
  java_microservice:
    group: microservices
    lock_behavior: unlockWhenFinished
    label_template: "${git_java_microservice}"
    materials: 
      git_java_microservice:
        git: https://github.com/mtararujs/api_tests_ci.git
        branch: main
        shallow_clone: true
        auto_update: true
    stages: 
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c 
                      - echo "Building java app"
      - deploy-dev:
          environment_variables:
            ENV_NAME: dev
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-dev:
          environment_variables:
            ENV_NAME: dev
          jobs:
            test:
              artifacts:
                - build:
                    source: report_dev.html
                    destination: test-output
              tabs:
                Report: test-output/report_dev.html
              tasks: *test-tasks
      - deploy-int:
          environment_variables:
            ENV_NAME: int
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-int:
          environment_variables:
            ENV_NAME: int
          jobs:
            test:
              artifacts:
                - build:
                    source: report_int.html
                    destination: test-output
              tabs:
                Report: test-output/report_int.html
              tasks: *test-tasks
      - deploy-prd:
          environment_variables:
            ENV_NAME: prd
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-prd:
          environment_variables:
            ENV_NAME: prd
          jobs:
            test:
              artifacts:
                - build:
                    source: report_prd.html
                    destination: test-output
              tabs:
                Report: test-output/report_prd.html
              tasks: *test-tasks