---
format_version: 10
pipelines:
  java_microservice:
    group: microservices
    lock_behavior: unlockWhenFinished
    label_template:
    materials: 
      git_java_microservice:
        git: https://github.com/mtararujs/api_tests_ci.git
        branch: main
        shallow_clone: true
        auto_update: true
    stages: 
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo "Building java app"

      - deploy-dev:
        jobs:
          build:
            tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - echo "deploying dev"

      - test-dev:
        jobs:
          build:
            tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - echo "testing-dev"

      - deploy-STG:
        jobs:
          build:
            tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - echo "deploying STG"

      - test-STG:
        jobs:
          build:
            tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - echo "testing-STG"

      - deploy-PRD:
        jobs:
          build:
            tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - echo "deploying PRD"

      - test-PRD:
        jobs:
          build:
            tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - echo "testing-PRD"